# Generated by Django 5.1.6 on 2025-04-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldTtance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='country',
            field=models.CharField(choices=[('USA', 'United States'), ('GBR', 'United Kingdom'), ('KEN', 'Kenya'), ('NGA', 'Nigeria'), ('UGA', 'Uganda'), ('IND', 'India'), ('CAN', 'Canada'), ('CHN', 'China'), ('JPN', 'Japan'), ('ABW', 'Aruba')], max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='country',
            field=models.CharField(choices=[('USA', 'United States'), ('GBR', 'United Kingdom'), ('KEN', 'Kenya'), ('NGA', 'Nigeria'), ('UGA', 'Uganda'), ('IND', 'India'), ('CAN', 'Canada'), ('CHN', 'China'), ('JPN', 'Japan'), ('ABW', 'Aruba')], default='KEN', max_length=5),
        ),
    ]
