# Generated by Django 5.1.6 on 2025-04-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldTtance', '0002_alter_recipient_country_alter_transaction_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='flutterwave_tx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
