# Generated by Django 5.1.6 on 2025-04-07 12:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorldTtance', '0004_alter_adminwallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=10),
        ),
    ]
